### ISSUE TITLE
Errors returned from decodeHeader claim to verify IsUnknownCharset but they don't

### ISSUE THREAD

**Issue by jameshoulahan** [emersion/go-message#107]
The header interface docstrings claim to return errors that verify `IsUnknownCharset` if the charset is unknown. This is not the case; the errors come from the internal implementation of `mime.WordDecoder.DecodeHeader` and aren't of the go-message `UnknownCharsetError` type.

A failing test can be found in https://github.com/emersion/go-message/pull/106.

Would you prefer to remove this from the docstring or come up with some ugly fix e.g. comparing error string values with the one returned from `DecodeHeader`?

```
// HeaderFields iterates over header fields.
type HeaderFields interface {
  ...
  // ... If the header field's charset is unknown,
  // the raw field value is returned and the error verifies IsUnknownCharset.
  Text() (string, error)
}
```

```
// ... If the header field's charset is unknown, the raw field
// value is returned and the error verifies IsUnknownCharset.
func (h *Header) Text(k string) (string, error) {
  return decodeHeader(h.Get(k))
}
```

**Comment by emersion** [comment]
Hmm. I think we should set `WordDecoder.CharsetReader` to a function that wraps the error, if any, in `UnknownCharset`.

**Comment by jameshoulahan** [comment]
I've updated #106 with a possible implementation of the wrapper. The test now passes.
