### ISSUE TITLE
nil pointer for quoted-printable encoded message with no body

### ISSUE THREAD

**Issue by y0ast** [emersion/go-message#108]
Hi, I recently got a nil pointer dereference crash in aerc and I was referred here to make the bug report.

For emails with an empty body, but `Content-Transfer-Encoding: quoted-printable`, go-message returns: a `*quotedprintable.Reader` with a nil pointer in it:

```
&{0xc000616000 <nil> []}
```

The mail was of the form (opening text/html was fine, it only crashes on text/plain):

```
From: Example <example@foo.bar>
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_11042185_1531286673.1599115134569"

------=_Part_11042185_1531286673.1599115134569
Content-Type: text/plain;charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-ID: text-body


------=_Part_11042185_1531286673.1599115134569
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-ID: html-body

<!DOCTYPE html (etc..)
```

For email with an empty body, but no specific `Content-Transfer-Encoding` go-message returns a `*bytes.Buffer` with a white line in it. This works fine.

**Comment by emersion** [comment]
Do you have a backtrace?

**Comment by y0ast** [comment]
Only from the aerc side:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5aed56]

goroutine 103 [running]:
bufio.(*Reader).fill(0xc000224060)
	/usr/lib/go/src/bufio/bufio.go:101 +0xd6
bufio.(*Reader).ReadSlice(0xc000224060, 0x10100000000000a, 0x0, 0x8000, 0xc0005b4000, 0x7f65243b3458, 0xc0005a2000)
	/usr/lib/go/src/bufio/bufio.go:360 +0x3d
mime/quotedprintable.(*Reader).Read(0xc000286060, 0xc0005b4000, 0x8000, 0x8000, 0x0, 0xc000353600, 0x40f8ac)
	/usr/lib/go/src/mime/quotedprintable/reader.go:87 +0x37a
io.copyBuffer(0xaf7e20, 0xc0006a6440, 0xaf6aa0, 0xc000286060, 0xc0005b4000, 0x8000, 0x8000, 0xc0005a2000, 0x472a40, 0xc0005a2000)
	/usr/lib/go/src/io/io.go:409 +0x12c
io.Copy(...)
	/usr/lib/go/src/io/io.go:368
os.genericReadFrom(0xc000432028, 0xaf6aa0, 0xc000286060, 0x0, 0x0, 0x0)
	/usr/lib/go/src/os/file.go:159 +0x99
os.(*File).ReadFrom(0xc000432028, 0xaf6aa0, 0xc000286060, 0x0, 0x0, 0x0)
	/usr/lib/go/src/os/file.go:153 +0x217
io.copyBuffer(0x7f652426d080, 0xc000246240, 0xaf6aa0, 0xc000286060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:395 +0x2ff
io.Copy(...)
	/usr/lib/go/src/io/io.go:368
git.sr.ht/~sircmpwn/aerc/widgets.(*PartViewer).attemptCopy.func1(0xc000438000)
	/home/joost/workspace/aerc/widgets/msgviewer.go:594 +0xbc
created by git.sr.ht/~sircmpwn/aerc/widgets.(*PartViewer).attemptCopy
	/home/joost/workspace/aerc/widgets/msgviewer.go:587 +0x65
```

**Comment by shamimevatix** [comment]
Similar Issue. I was trying to read text, HTML parts of an incoming email from hotmail. But looks like the mail reader can't decode it due to 
[from-hotmail.txt](https://github.com/emersion/go-message/files/5208458/from-hotmail.txt)
[twitter.txt](https://github.com/emersion/go-message/files/5208474/twitter.txt)

Here is the code

package main

import (
	"github.com/emersion/go-message"
	"github.com/emersion/go-message/mail"
	"io"
	"io/ioutil"
	"log"
	"strings"
	"testing"
)

func TestSpamEmailSubject(t *testing.T) {
	header := "=?UTF-8?B?RVhDTFVTSVZFISBTaXggc3VyZS1maXJlIFdheXMgdG8gU2FmZWd1YXJkIFlvdXIgUGV0IGFnYWluc3QgQ29tbW9uIERpc2Vhc2Vz==?="
	header = "=?iso-8859-16?Q?Yahoo_+_Sample?="

	subject, err := message.DecodeHeader(header)
	if err != nil {
		t.Errorf("decode error " + err.Error())
	} else {
		log.Println("subject,", subject)
	}

}

func TestParseIncomingEmailFromHotmail(t *testing.T) {
	f, _ := ioutil.ReadFile("from-hotmail.txt")
	//f, _ := ioutil.ReadFile("twitter.txt") //it works


	mailBody := strings.NewReader(string(f))
	mailReader, err := mail.CreateReader(mailBody)
	if err != nil {
		log.Println("mail reader create error", err.Error())
	}

	header := mailReader.Header
	log.Println("From", header.Get("From"))
	messageId := header.Get("Message-ID")
	log.Println("messageId", messageId)

	for {
		mailBodyPart, err := mailReader.NextPart()
		if err == io.EOF {
			log.Println("eof error")
			break
		} else if err != nil {
			log.Println("other error", err.Error())
			t.Errorf("other error " + err.Error())
			break
		}

		switch h := mailBodyPart.Header.(type) {
		case *mail.AttachmentHeader:
			filename, _ := h.Filename()
			log.Println("This part is mail.AttachmentHeader", "filename", filename)
		case *mail.InlineHeader:
			log.Println("This part is mail.InlineHeader")
		}
	}
}

output
--- FAIL: TestParseIncomingEmailFromHotmail (0.00s)
    main_test.go:48: other error message: unhandled charset "iso-8859-1"
FAIL

Maybe, it is an easy fix for you. But I am getting lost while fixing this. 

Also, TestSpamEmailSubject does not pass with the current library. I have resolved it by using a refactored version of "mime" by me.

**Comment by y0ast** [comment]
My bug seemed to not have been a problem with go-message, a go-message test parses my email fine.

@shamimevatix Given it's not the same bug, it's probably worth opening a separate bug for your issue.

**Comment by shamimevatix** [comment]
Thank you very much @y0ast . I have solved it anyway.

**Comment by Massolari** [comment]
@shamimevatix How did you solve it? I'm having the same problem
