### ISSUE TITLE
Failed to decode "iso-2022-jp"

### ISSUE THREAD

**Issue by ly020044** [emersion/go-message#117]
Hi,

please help me.
`package main`

`import (`
	`"github.com/emersion/go-message"`
	`"os"`

	_ "github.com/emersion/go-message/charset"
`)`

`func main() {`
	`msg, err := message.Read(os.Stdin)`
	`if err != nil {`
		`println(err.Error())`
		`return`
	`}`
	`print(msg.Header.Get("Subject"))`
`}`

print:: =?ISO-2022-JP?B?GyRCTCQ+NUJ6OHg5cCIoIzUjMCMwIzAxXyRHMys2SCQ3GyhC?= =?ISO-2022-JP?B?GyRCJF4kOyRzJCshKiEqGyhC?=

**Comment by emersion** [comment]
`Get` doesn't decode anything. Use `Text` to instead.
