### ISSUE TITLE
Only supports 2 character sets on Entity.WriteTo()

### ISSUE THREAD

**Issue by ly020044** [emersion/go-message#127]
Hi,

I will create test mail,  but set conent type parames only support utf-8 and us-ascii.

**Source Url**
https://github.com/emersion/go-message/blob/master/writer.go#L58

**Example**
`
func main() {
	var header message.Header
	//header.SetContentType("text/plain", map[string]string{"charset": "utf-8"})
	header.SetContentType("text/plain", map[string]string{"charset": "iso-8859-1"})
	header.Set("From", "a@test.org")
	header.Set("To", "b@test.io")

	entity, err := message.New(header, bytes.NewBufferString("hello world"))
	if err != nil {
		fmt.Println(err)
		return
	}

	f, err := os.OpenFile("./test.eml", os.O_CREATE|os.O_RDWR, 0644)
	if err != nil {
		fmt.Println(err)
		return
	}

	err = entity.WriteTo(f)
	if err != nil {
		fmt.Println(err)
	}
}
`

**Error**
`unknown charset: unknown charset: message: unhandled charset "iso-8859-1"`

>

**Comment by emersion** [comment]
Yes, that's by design. You shouldn't use anything other than these two.

**Comment by iredmail** [comment]
I think utf-8 and us-ascii should be RECOMMENDED but not forced, since `message.Read()` supports it (`iso-8859-1`).

**Comment by emersion** [comment]
We support many charsets for reading, because unfortunately many email messages still use these.

Use UTF-8 for writing. Other charsets are just artifacts from the past, I will NACK their support.

**Comment by iredmail** [comment]
For writing a new email, it's ok to use just utf-8, but if you need to read first then modify, this is not gonna work.
Again, using utf-8/us-ascii should be strongly recommended, but not forced.

**Comment by emersion** [comment]
If you need to read, you're already decoding to UTF-8.

**Comment by iredmail** [comment]
As mentioned in above replies, we read first, but we need to keep the entity header and replace its body.

**Comment by emersion** [comment]
Then this isn't supported by the message package. You can use the go-message/textproto package if you want to opt-out of encoding/charset handling.

**Comment by iredmail** [comment]
I suggest recommending utf-8 and us-ascii for writing NEW message, but also allow to use other charsets for best compatibility.

We just need to replace body of a `iso-8859-1` entity by a shasum256 string, no need for encoding/charset handling. :)

**Comment by emersion** [comment]
As I said above, I don't want to support writing messages with anything other than UTF-8. If you want to, feel free to implement your own thing. Supporting other charsets for reading is already causing me enough trouble.

> We just need to replace body of a iso-8859-1 entity by a shasum256 string, no need for encoding/charset handling. 

Why do you need to do this? And why use the go-message package instead of go-message/textproto?

**Comment by mooijtech** [comment]
For future reference you can work around the "unhandled charset" error when writing by setting the Content-Type to "utf-8" on the header.
