### ISSUE TITLE
Header.AddressList does not do RFC2047 header decoding

### ISSUE THREAD

**Issue by macfisherman** [emersion/go-message#132]
https://github.com/emersion/go-message/blob/981888ca7c0807f5dca8fb8e167cb5da3c0bfcd5/mail/header.go#L229

Program that shows the problem:

        import (
	        "bytes"
	        "fmt"
	        "log"
	        "strings"
        
	        _ "github.com/emersion/go-message/charset"
	        "github.com/emersion/go-message/mail"
        )
        
        func main() {
	        raw := `From: =?utf-8?q?Atakan_=C3=87olak?= <atakancolak9897@example.org>
        
        message body
        `
	        raw = strings.ReplaceAll(raw, "\n", "\r\n")
	        msg := bytes.NewReader([]byte(raw))
        
	        m, err := mail.CreateReader(msg)
	        if err != nil {
		        log.Fatal(err)
	        }
        
	        from, err := m.Header.AddressList("From")
	        if err != nil {
		        log.Fatal("From: ", err)
	        }
	        fmt.Println(from) // quoted part of address wasn't decoded
        
	        decoded, err := m.Header.Text("From") // quoted part decoded 
	        if err != nil {
		        log.Fatal(err)
	        }
	        fmt.Println(decoded)
    }

output:

        Jeffs-MBP-2:mbox-bug jeff$ go run . 
        [=?utf-8?q?Atakan_=C3=87olak?= <atakancolak9897@example.org>]
        Atakan Çolak <atakancolak9897@example.org>

It seems like h.Text() should be used instead of h.Get()?

https://github.com/emersion/go-message/blob/981888ca7c0807f5dca8fb8e167cb5da3c0bfcd5/mail/header.go#L230

**Comment by macfisherman** [comment]
I'm not sure what is happening here. Here is a debug session, with no changes to the code. While Header.Get doesn't decode, the call to ParseAddressList  does at some point.


        Jeffs-MBP-2:mbox-bug jeff$ dlv debug main.go
        Type 'help' for list of commands.
        (dlv) b main.go:28
        Breakpoint 1 set at 0x119da34 for main.main() ./main.go:28
        (dlv) c
        > main.main() ./main.go:28 (hits goroutine(1):1 total:1) (PC: 0x119da34)
            23:		m, err := mail.CreateReader(msg)
            24:		if err != nil {
            25:			log.Fatal(err)
            26:		}
            27:	
        =>  28:		from, err := m.Header.AddressList("From")
            29:		if err != nil {
            30:			log.Fatal("From: ", err)
            31:		}
            32:	
            33:		spew.Dump(from)
        (dlv) n
        > main.main() ./main.go:29 (PC: 0x119db16)
            24:		if err != nil {
            25:			log.Fatal(err)
            26:		}
            27:	
            28:		from, err := m.Header.AddressList("From")
        =>  29:		if err != nil {
            30:			log.Fatal("From: ", err)
            31:		}
            32:	
            33:		spew.Dump(from)
            34:		fmt.Printf("%s\n%v\n%+v\n", from, from, from)
        (dlv) p from
        []*net/mail.Address len: 1, cap: 1, [
	        *{
		        Name: "Atakan Çolak",
		        Address: "atakancolak9897@example.org",},
        ]
        (dlv) p from[0]
        *net/mail.Address {
	        Name: "Atakan Çolak",
	        Address: "atakancolak9897@example.org",}
        (dlv) p from[0].Name
        "Atakan Çolak"
        (dlv) n
        > main.main() ./main.go:33 (PC: 0x119dc34)
            28:		from, err := m.Header.AddressList("From")
            29:		if err != nil {
            30:			log.Fatal("From: ", err)
            31:		}
            32:	
        =>  33:		spew.Dump(from)
            34:		fmt.Printf("%s\n%v\n%+v\n", from, from, from)
            35:	
            36:		decoded, err := m.Header.Text("From")
            37:		if err != nil {
            38:			log.Fatal(err)
        (dlv) n
        ([]*mail.Address) (len=1 cap=1) {
         (*mail.Address)(0xc00000e3e0)(=?utf-8?q?Atakan_=C3=87olak?= <atakancolak9897@example.org>)
        }
        > main.main() ./main.go:34 (PC: 0x119dcfa)
            29:		if err != nil {
            30:			log.Fatal("From: ", err)
            31:		}
            32:	
            33:		spew.Dump(from)
        =>  34:		fmt.Printf("%s\n%v\n%+v\n", from, from, from)
            35:	
            36:		decoded, err := m.Header.Text("From")
            37:		if err != nil {
            38:			log.Fatal(err)
            39:		}
        (dlv) n
        [=?utf-8?q?Atakan_=C3=87olak?= <atakancolak9897@example.org>]
        [=?utf-8?q?Atakan_=C3=87olak?= <atakancolak9897@example.org>]
        [=?utf-8?q?Atakan_=C3=87olak?= <atakancolak9897@example.org>]
        > main.main() ./main.go:36 (PC: 0x119deba)
            31:		}
            32:	
            33:		spew.Dump(from)
            34:		fmt.Printf("%s\n%v\n%+v\n", from, from, from)
            35:	
        =>  36:		decoded, err := m.Header.Text("From")
            37:		if err != nil {
            38:			log.Fatal(err)
            39:		}
            40:	
            41:		fmt.Println(decoded)
        (dlv) p from
        []*net/mail.Address len: 1, cap: 1, [
	        *{
		        Name: "Atakan Çolak",
		        Address: "atakancolak9897@example.org",},
        ]

**Comment by emersion** [comment]
Yeah, `mail.ParseAddressList` is supposed to do the decoding.

Maybe try this?

```go
fmt.Println(from.Name)
```

The `Address.String` function re-encodes the address.

**Comment by macfisherman** [comment]
Thank you, yes, that works (as from[0].Name). I would of expected the String method on the struct to do the same.

**Comment by emersion** [comment]
That function lives in the standard Go library, so not much we can do about it.

**Comment by macfisherman** [comment]
Ah, I see now, we are actually dealing with a net/mail.Address. To bad something like this couldn't be done:

        func (a Address) String() string {
	        return a.Name + " " + a.Address
        }

**Comment by ahmedkhalf** [comment]
I am still having this issue even after the proposed solution...

```
mr, err := mail.CreateReader(r)
header := mr.Header
if from, err := header.Text("From"); err == nil {
        log.Println("From:", from[0].Name)
}
```
output:
```
2021/03/15 14:52:16 From: =?utf-8?q?=E2=99=9F?=Chess.com
```

**Comment by emersion** [comment]
This one sounds different. Please open a new issue with the original From header value.
