### ISSUE TITLE
header.AddressList does not decode header Name

### ISSUE THREAD

**Issue by ahmedkhalf** [emersion/go-message#133]
Here is the name of the email I am trying to decode: `♟Chess.com`
My code:
```golang
r := msg.GetBody(section) // go-imap
mr, err := mail.CreateReader(r)
header := mr.Header
if from, err := header.AddressList("From"); err == nil {
        log.Println("From:", from)
}
```
output:

```
2021/03/15 15:08:53 From: ["=?utf-8?q?=E2=99=9F?=Chess.com" <alert@chess.com>]
```

I tried use from.Name as suggested here (https://github.com/emersion/go-message/issues/132#issuecomment-788762616).
But still doesn't work: (https://github.com/emersion/go-message/issues/132#issuecomment-799321271)

**Comment by emersion** [comment]
What is the raw header value?

```go
header.Get("From")
```

**Comment by ahmedkhalf** [comment]
```log.Println(header.Get("From"))```
```2021/03/15 15:15:59 "=?utf-8?q?=E2=99=9F?=Chess.com" <alert@chess.com>```

**Comment by emersion** [comment]
The name is quoted. UTF-8 escaping can't happen inside of quoted strings. The original header is broken.

**Comment by ahmedkhalf** [comment]
But what do I do now? This is comes from outlook.. Is there any other alternative in go-imap to fetch the name?

**Comment by emersion** [comment]
Outlook well known for correctly implementing RFCs as always…

If you really want to work around the issue you can pass the value through `textproto.WordDecoder` again. This isn't a patch I'd accept upstream though.
