### ISSUE TITLE
Get attachment input stream

### ISSUE THREAD

**Issue by mooijtech** [emersion/go-message#147]
Hello emersion,

Is it possible to get the attachment input stream and write it to a file?
Even the base64 as a value would do as I could decode it and write it to a file.

Kind regards,
Marten Mooij

**Comment by emersion** [comment]
Please don't use GitHub issues to ask questions. GitHub issues are for feature requests or bug reports only.

**Comment by mooijtech** [comment]
Alright, my apologies.

I just found that your library automatically decodes attachments into the Body so that solves my question.
I should probably figure this out on my own instead of asking first, my bad.
