### ISSUE TITLE
Cannot add a message/rfc822 part correctly (Content-Transfer-Encoding is not valid)

### ISSUE THREAD

**Issue by Spiral90210** [emersion/go-message#153]
When creating mails, the library does not allow correct embedding of `message/rfc822` parts. When adding a mime part like this, the contents _must not_ be transfer encoded - they are assumed to be already encoded because mime by definition is already transport safe. However, this function does not account for this:

```go
func initInlineContentTransferEncoding(h *message.Header) {
	if !h.Has("Content-Transfer-Encoding") {
		t, _, _ := h.ContentType()
		if strings.HasPrefix(t, "text/") {
			h.Set("Content-Transfer-Encoding", "quoted-printable")
		} else {
			h.Set("Content-Transfer-Encoding", "base64")
		}
	}
}
```

And it's usage:

```go
func encodingWriter(enc string, w io.Writer) (io.WriteCloser, error) {
	var wc io.WriteCloser
	switch strings.ToLower(enc) {
	case "quoted-printable":
		wc = quotedprintable.NewWriter(w)
	case "base64":
		wc = base64.NewEncoder(base64.StdEncoding, textwrapper.NewRFC822(w))
	case "7bit", "8bit":
		wc = nopCloser{textwrapper.New(w, "\r\n", 1000)}
	case "binary", "":
		wc = nopCloser{w}
	default:
		return nil, fmt.Errorf("unhandled encoding %q", enc)
	}
	return wc, nil
}
```

The only valid encodings for a part like this are `7bit`, `8bit` and `binary`. This is in RFC-2048 5.2.1 https://datatracker.ietf.org/doc/html/rfc2046#section-5.2.1

> No encoding other than "7bit", "8bit", or "binary" is permitted for
   the body of a "message/rfc822" entity.  The message header fields are
   always US-ASCII in any case, and data within the body can still be
   encoded, in which case the Content-Transfer-Encoding header field in
   the encapsulated message will reflect this.  Non-US-ASCII text in the
   headers of an encapsulated message can be specified using the
   mechanisms described in [RFC 2047](https://datatracker.ietf.org/doc/html/rfc2047).
   
This is actually true for both inline and attachment headers, I've just shown inline. I'll make a PR to handle both because I need this anyway :)

**Comment by emersion** [comment]
`initInlineContentTransferEncoding` is only called with `NewInlineWriter` which doesn't seem like it's the right function to call here?

**Comment by Spiral90210** [comment]
I was following the examples, and had code like this:

```go
var msgPartHeader mail.InlineHeader
msgPartHeader.Set("Content-Type", "message/rfc822")
msgPart, err := rootWriter.CreateSingleInline(msgPartHeader)
// calls to  msgPart.Write([]byte)
```

Is there a better way to do this? It has to be inline, can't be an attachment. Ideally the only header here is Content-Type. Perhaps there is a better way to do this that I have missed? The only options I seem to have are screenshotted.

<img width="575" alt="Screenshot 2022-04-11 at 15 35 24" src="https://user-images.githubusercontent.com/8685965/162763027-72a81a90-0270-4b8a-96e7-aaa8bbd938b2.png">

**Comment by emersion** [comment]
The `mail` package is opinionated and only knows about inline parts (email text) and attachments parts.

**Comment by Spiral90210** [comment]
Would you have an interest in merging a PR that accepted message/rfc822? If not I can maintain it in my fork (I have to do that anyway unless https://github.com/emersion/go-message/pull/152 is accepted), but I think support can be added in a trivial way.

I imagine it to be just extending this func:

```go
func initInlineContentTransferEncoding(h *message.Header) {
	if !h.Has("Content-Transfer-Encoding") {
		t, _, _ := h.ContentType()
		if strings.HasPrefix(t, "text/") {
			h.Set("Content-Transfer-Encoding", "quoted-printable")
		} else if strings.EqualFold(t, "message/rfc822") {
			h.Set("Content-Transfer-Encoding", "binary") // or don't set at all
		} else {
			h.Set("Content-Transfer-Encoding", "base64")
		}
	}
}
```

I think I'd rather not set the transfer encoding, and modify `createWriter(w io.Writer, header *Header)` (which is already multipart aware) to also be aware of this content type, but it might be possible to just set binary here - my plan was to try binary first and see how messages are shown/handled in regular mail clients - I think it _should_ work, but I've never seen it in the wild.

Attachments of message/rfc822 type _should_ also be handled this way, as the spec does say to avoid double encoding, so I just had a look at that, and realised I can just override the transfer encoding myself (`if !h.Has("Content-Transfer-Encoding")` - I guess I jumped straight to "the library should do it for me" rather than actually taking the time to read properly...), so I can experiment with binary at least, see how it works.

Either way, I believe it should be a small change. I'll let you know - if binary works ok with mail clients then this just becomes a nice to have.

**Comment by emersion** [comment]
I don't really understand how a user agent is supposed to display an inline `message/rfc822` part.

**Comment by Spiral90210** [comment]
Sorry for the late reply - typically they just show it as an attachment (despite it being inline). I would agree that's weird and it would be better suited being an explicit attachment, but that's the format that Exchange uses with journal reports - literally a single header, and I'm replicating that.

```
Content-Type: message/rfc822
```

The same holds true for attachments though - message/rfc822, regardless of disposition, should not be encoded. 

Here's a screengrab of what outlook does - it's only a portion because I'm terrible at editing images to redact information from them! Yes, the subject is in hebrew, and that's what is being used as the 'name' of the attachment.

<img width="288" alt="Screenshot 2022-04-20 at 14 49 58" src="https://user-images.githubusercontent.com/8685965/164245519-a403a86f-71fe-408e-bdc2-f1b3cadc8ba7.png">

Thunderbird on the other hand, displays the message inline, with some headers (the original content is displayed too - again I'm terrible at redaction so just snipped a bit):

<img width="74" alt="Screenshot 2022-04-20 at 14 52 14" src="https://user-images.githubusercontent.com/8685965/164246039-b9dfe63a-e6a8-4a22-bebb-328f983d30d8.png">

**Comment by Spiral90210** [comment]
Apple Mail... I don't know what it's trying to do when I try and open the file but I've never set it up before and it's complaining about icloud things needing setup instead of just displaying the darn email, so consider that a bust. Fairly typical in my experience of it, not exactly developer friendly.

**Comment by emersion** [comment]
The `mail` package is opinionated. It isn't designed to create weird emails, e.g. with inline `message/rfc822` parts. It's designed to create emails with an inline text part and optional attachments.

If you need more control, use the `message` package.

**Comment by Spiral90210** [comment]
Fair enough, didn't realise that was an option from the docs! I've confirmed my use case works with the binary type btw, though there are extra headers I'd rather remove but it shouldn't be an issue - closing this.

Thanks for responding!
