### ISSUE TITLE
default charset?

### ISSUE THREAD

**Issue by schmitch** [emersion/go-message#25]
hello, I've stumbled upon your library and it's really great for me.

However I stumbled upon a line that might be wrong:
https://github.com/emersion/go-message/blob/master/entity.go#L52
shouldn't there be a default encoding of ASCII i.e. windows1252?

Currently if an email does not define an encoding it is normally encoded in ascii.

The code should probably be something like:
```
ch, ok := mediaParams["charset"]
if ! ok {
    ch = "ascii"
}
if converted, charsetErr := charset.Reader(ch, body); charsetErr != nil {
    err = unknownEncodingError{charsetErr}
} else {
    body = converted
}
```

(couldn't find a appropriate rfc yet)

**Comment by emersion** [comment]
If there's no encoding, ASCII is assumed so there's no need to convert `body` into UTF-8 - ASCII is already valid UTF-8 and we can read it as-is.

**Comment by schmitch** [comment]
thanks, for the quick reply and explanation!
