### ISSUE TITLE
Support internationalized headers

### ISSUE THREAD

**Issue by hartshorne** [emersion/go-message#3]
Python's email package is able to handle these: https://docs.python.org/2/library/email.header.html

**Comment by emersion** [comment]
You're totally right. Maybe the Get, Set and Add functions should always encode and decode the header's content?

**Comment by hartshorne** [comment]
Yes, I think that seems reasonable.

**Comment by emersion** [comment]
I finally added `mail/Header.Subject` and `mail/Header.SetSubject`. I'm not sure which other fields need internationalization, apart from mails' subjects and attachments' filenames.

Maybe adding a getter and setter for each header field defined in the RFC would be a good idea? There aren't many of them, and many mail headers are already covered. This would require to define a `message.Header` type (to parse `Content-Type` and other fields).

Also, I haven't exported functions to encode and decode headers. Maybe this could be useful for headers not defined in those RFCs?

**Comment by hartshorne** [comment]
Python handles it this with keyword arguments and magic tuples: https://github.com/python/cpython/blob/master/Lib/email/message.py#L515

But it's pretty awkward to use. 

I think adding Getter/Setters for each header in the RFC would be nicest to use, and the simplest thing to build/test. Probably don't need to export the encode/decode functions for now. It's easy to export them later if needed.
