### ISSUE TITLE
Read part

### ISSUE THREAD

**Issue by djeckson** [emersion/go-message#31]
I need to get only the text of the letter, without attachments. I get it through my `BODY[1]` When I try to read, I get an error: `malformed MIME header line: ------=_Part_431250_2039599834.1547645922837`, if I add `BODY[HEADER], BODY[1]` when searching, then the answer is in different Body section

**Comment by emersion** [comment]
Try `BODY[]`?

**Comment by djeckson** [comment]
body [] returns all parts, and I only need the part with text

**Comment by emersion** [comment]
Ah, I misread. Can you get a dump of `BODY[]` and `BODY[1]`? IIRC `BODY[1]` is supposed to work, maybe a malformed message?

**Comment by djeckson** [comment]
It doesn't work when Content type is multipart/alternative and consists of text/plain and text/html and I'm trying to get one of the parts

**Comment by emersion** [comment]
You should be able to use `BODYSTRUCTURE` to select the correct part.

In any case, this is not a go-message issue.
