### ISSUE TITLE
Additional ascii charset

### ISSUE THREAD

**Issue by urlund** [emersion/go-message#35]
I've encountered several cases where a message has "utf-ascii" charset so I've tried to add it as a valid charset, like "us-ascii", and it works as exptected (in my cases). 

Could you consider doing the same?
(I'll create a PR, if you like)

**Comment by emersion** [comment]
This is definitely non-standard. Can't you ignore `IsUnknownCharset` errors instead?

**Comment by urlund** [comment]
Ahh, ofc. Thanks.

I changed my code to check if `IsUnknownCharset` and further more to verify that err message contains `utf-ascii`.
