### ISSUE TITLE
Fetching message documentation error

### ISSUE THREAD

**Issue by Meowzz95** [emersion/go-message#36]
[Fetching message Doc](https://github.com/emersion/go-imap/wiki/Fetching-messages)

This section:

```go
switch h := p.Header.(type) {
		case mail.TextHeader:
			// This is the message's text (can be plain-text or HTML)
			b, _ := ioutil.ReadAll(p.Body)
			log.Println("Got text: %v", string(b))
		case mail.AttachmentHeader:
			// This is an attachment
			filename, _ := h.Filename()
			log.Println("Got attachment: %v", filename)
		}
```

`TextHeader` does not even exist... I changed it to `InlineHeader` then it gives the following error.

`impossible type switch case: part.Header (type "github.com/emersion/go-message/mail".PartHeader) cannot have dynamic type "github.com/emersion/go-message/mail".InlineHeader (Add method has pointer receiver)`

and

`impossible type switch case: part.Header (type "github.com/emersion/go-message/mail".PartHeader) cannot have dynamic type "github.com/emersion/go-message/mail".AttachmentHeader (Add method has pointer receiver)
`

And I can't find a way to find out the header... Any idea?

**Comment by DeadNumbers** [comment]
Look this commit https://github.com/emersion/go-message/commit/4835456659a2469969d9aad0e3c71f3270022cbc

```Go
switch h := p.Header.(type) {
		case *mail.InlineHeader:
			// This is the message's text (can be plain-text or HTML)
			b, _ := ioutil.ReadAll(p.Body)
			log.Println("Got text: %v", string(b))
		case *mail.AttachmentHeader:
			// This is an attachment
			filename, _ := h.Filename()
			log.Println("Got attachment: %v", filename)
		}
```

**Comment by foxcpp** [comment]
Thanks for the pointer, DeadNumbers. I updated the go-imap wiki page to reflect changes in go-message.

**Comment by Meowzz95** [comment]
@DeadNumbers Thanks, I figured it out by checking the test code in master branch...

**Comment by ferhatelmas** [comment]
section part also has an issue because `msg.GetBody(section)` call requires pointer.
