### ISSUE TITLE
Tagging a new release

### ISSUE THREAD

**Issue by andystroz** [emersion/go-message#46]
Hey! you have added the ability to decode more types of message charsets in your master branch. Could you tag a new release with those features @emersion ? 

BTW really love your go email libraries so far.

**Comment by andystroz** [comment]
Managed to get it to work with `go get github.com/emersion/go-message@5c83a6521b32987178c796706447a226443bfb7f` would be great to have a new release though with the new encoding types :)

**Comment by emersion** [comment]
Which commit are you interested in actually? There are only two commits since the last release: https://github.com/emersion/go-message/compare/v0.10.3...master

**Comment by andystroz** [comment]
ah thats weird... I was getting an error decoding an email with `iso-8859-1` and it seems as though it was because the version of `go-message` I was using wasn't actually `v0.10.3`. Updating to `v0.10.3` which moved charset to its own folder fixed it. (The version I was using had `charset.go` in the root folder. 

https://github.com/emersion/go-message/blob/master/charset/charset.go
