### ISSUE TITLE
Tag master for vgo

### ISSUE THREAD

**Issue by signedbit** [emersion/go-message#58]
Hi Emersion,

Thanks so much for the great library! 

GoLand synced `go.mod` with v0.10.7 but build fails with:

`header.Len undefined (type *"github.com/emersion/go-message/mail".Header has no field or method Len)`

Compared master and v0.10.7 tag, bug is fixed in master. Can you tag master as v0.10.8 please? 

Thanks!

**Comment by foxcpp** [comment]
Btw, you can use the latest commit from master this way:
```
go get github.com/emersion/go-message@master
```

**Comment by emersion** [comment]
Released 0.10.8.

**Comment by signedbit** [comment]
@foxcpp Yes, adding `require github.com/emersion/go-message master` to `go.mod` also works but could cause a build failure during a major version bump. That would defeat the purpose of [Go modules](https://github.com/golang/go/wiki/Modules)!

`require github.com/emersion/go-message v0.10.8-0.20191016211634-85cd354f5485` also works but is ugly.

This was originally caused by first using `go get`, then opting-in to Go modules. Since the latest available tag was v0.10.7, that's what got written to the `go.mod` file. Unfortunately, the code already depended on a commit that came after tag v0.10.7 but before tag v0.10.8.
