### ISSUE TITLE
Option to turn off auto encoding and charset handling

### ISSUE THREAD

**Issue by digitive** [emersion/go-message#62]
First I want to say that this library is really awesome! Huge thanks.

I hope we can have an option to turn off the auto encoding/decoding and charset handling feature. 

The reason is:
1. There are too many non-conformant email in the real world and we will want to handle them in a customized way. For example, we optionally process those with supported charset, and bypass those unknown charset instead of failure.
2. There are some cases that encoding/decoding are not necessary. Turn it off will increase the performance 

Thank you

**Comment by foxcpp** [comment]
You can use textproto subpackage directly to read the header (it will not decode fields) and then take care of the body how you want. Then you probably would have to handle CTE as well, but that does not seem to be difficult: https://github.com/emersion/go-message/blob/master/encoding.go

**Comment by digitive** [comment]
That sounds a good solution. Let me try. Thank you!
