### ISSUE TITLE
Add a package with all charsets

### ISSUE THREAD

**Issue by emersion** [emersion/go-message#64]
It seems some people don't care about binary size and want to register all charsets supported by the Go `x/text/encoding` library. We could add a `charset/all` package which registers all of them.

**Comment by MyeongkookKim** [comment]
I can't use this package because not support korean. so this is great idea release version of all charset included.

**Comment by emersion** [comment]
I've decided to add support for all charsets in the `charset` package directly since this only adds 100KiB (which isn't a lot when the current `charset` package is almost 1MiB).
