### ISSUE TITLE
Handle MIME-encoded address list headers

### ISSUE THREAD

**Issue by benburwell** [emersion/go-message#67]
Currently, in mail/header.go, we use `h.Get(key)` to grab the header to
parse. Sometimes, address list headers include MIME-encoded segments,
particularly in the display names. Currently, we don't decode these
segments. Is this a bug? Is there some reason we shouldn't be using
`h.Text(key)` instead?

Happy to send a patch, just wanted to check if it is a valid fix first.

**Comment by emersion** [comment]
We use `mail.AddressParser`, which handles this: https://github.com/emersion/go-message/blob/71005f4b31f35eaaee0cb5610f8b25f285fe74a5/mail/address.go#L22

**Comment by benburwell** [comment]
Yep -- here is a reproducer for the issue I was seeing in a message I
received recently:

    package main

    import (
      "log"
      "github.com/emersion/go-message/mail"
    )

    func main() {
      var h mail.Header
      h.Set("From", `"=?US-ASCII?Q?Federal_Aviation_Administration?=" <usafaa@public.govdelivery.com>`)
      addrs, err := h.AddressList("From")
      if err != nil {
        log.Fatal(err)
      }
      for _, addr := range addrs {
        log.Printf("name: %s", addr.Name)
      }
    }

This program outputs

    2020/01/06 09:46:39 name: =?US-ASCII?Q?Federal_Aviation_Administration?=

On closer reading of RFC 2047 (5)(3), "An 'encoded-word' MUST NOT appear
within a 'quoted-string'", so it looks like this is just an invalid
header; without the surrounding double quotes, go-message (thru
net/mail) decodes the MIME as expected. Sorry for the noise!
