### ISSUE TITLE
message: unhandled charset "utf8"

### ISSUE THREAD

**Issue by caiqing0204** [emersion/go-message#74]
mr, err := mail.CreateReader(r)
		if err != nil {
			log.Fatal(err)
		}

**Comment by emersion** [comment]
Do you import the charset package?

```
import _ "github.com/emersion/go-message/charset"
```

**Comment by foxcpp** [comment]
I guess it would be a good idea to handle "utf8" by default.

**Comment by emersion** [comment]
Yeah. And move the ASCII quirks over too.

**Comment by caiqing0204** [comment]
mr, err := mail.CreateReader(r)
	if err != nil {
		log.Fatal(err)
	}

**Comment by emersion** [comment]
Hm. We're going to need more details.

**Comment by caiqing0204** [comment]
> Hm. We're going to need more details.
My code execution logic looks like this

`	// Connect to server
	c, err := client.DialTLS(*server, nil)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Connected")

		// Create a new mail reader
		mr, err := mail.CreateReader(r)
		if err != nil {
			log.Fatal(err)
		}
`
Here, ”mr, err := mail.CreateReader(r)“ find error  **message: unhandled charset "utf8"** ,This output is from err,The subject of my email contains both Chinese and English, and there is no problem with the subject in English, but such problems with the subject in Chinese make me really upset.

**Comment by emersion** [comment]
Please reply to my question in https://github.com/emersion/go-message/issues/74#issuecomment-591896642

>make me really upset

Just for the record, don't expect reported bugs to get fixed magically. This is an open-source project: if someone really wants to get a bug fixed, they need to submit a patch.

**Comment by emersion** [comment]
After thinking about this, I think I'd be against handling non-standard charsets out-of-the-box. The non-standard charset list would need to be duplicated between go-message, go-message/charset and go-imap. I don't want to maintain 3 different lists.
