### ISSUE TITLE
textproto.ReadHeader() panics when nil Reader is passed

### ISSUE THREAD

**Issue by aleksatr** [emersion/go-message#76]
https://github.com/emersion/go-message/blob/9c4415ed8676c8c7a266e0c1713ffb104f51637d/textproto/header.go#L435

Peeking the `nil` `*bufio.Reader` will result in panic. Maybe worth adding a `nil` check for this case? 
If you think that it should be solved on the caller side, I can submit a patch for koushin that would avoid this panic?

**Comment by foxcpp** [comment]
Is it common to use `nil` io.Reader to indicate an empty stream or something? How standard library handles this? It might be worth fixing on the koushin side instead.

**Comment by emersion** [comment]
Yes, this seems like a koushin bug. Thanks for finding this, feel free to submit a koushin patch. :)
