### ISSUE TITLE
message: unhandled charset "iso-8859-1"

### ISSUE THREAD

**Issue by razorness** [emersion/go-message#78]
Email with Header `Content-Type: text/html; charset="iso-8859-1"` is throwing following error:

`message: unhandled charset "iso-8859-1"`
at https://github.com/emersion/go-message/blob/master/entity.go#L50

This encoding is very common in western europe. Any idea how to avoid this?

**Comment by emersion** [comment]
Add `import _ "github.com/emersion/go-message/charset"`.
