### ISSUE TITLE
RFC 5322 character use limitation

### ISSUE THREAD

**Issue by dvalter** [emersion/go-message#80]
RFC 5322 limits use of characters in general (US-ASCII) and for some specific scopes. For example in headers only printable ASCII characters (`'!'..'~'`), SPACE and HTAB are allowed and `\r\n ` sequence is used for line folding.

It's currently possible to pass some disallowed symbols to go-message. The most noticeably it's a single `\n` in header values which is treated as a regular symbol or a part of `\r\n ` sequence. As it was discussed in #77, the best way of handling such cases is just failing with an explicit error.

I have a few possible solutions. but I don't feel like any of them is clearly "the best":
* checking whether `\n` is a part of the folding sequence; solves only a subproblem, but does not change behavior on externally folded line
* Matching strings with a regex (`"[\t -~]*"` for headers); probably the most clean, but may be not great in terms of performance
* Manually checking strings symbol by symbol, may introduce some possible optimizations like single pass `foldLine` but certainly is not as fancy as the previous one.

I don't know what would be better to implement (or maybe I don't see something else), so I'd like to discuss it here before coding.

**Comment by foxcpp** [comment]
[RFC 6532](https://tools.ietf.org/html/rfc6532) relaxes that limitation by also allowing all UTF-8.

**Comment by emersion** [comment]
We already have `Header.AddRaw` for externally-folded lines. I think we should just disallow `\n` in the folding algorithm's input.

**Comment by dvalter** [comment]
> I think we should just disallow \n in the folding algorithm's input.

It's likely to be enough for field values, but field names may still be broken in similar to #68 way. I believe the best place to add these checks is `Header.Add`.
According to RFC 6532, fairly reasonably mentioned by @foxcpp, key should be checked against "printable US-ASCII except colon" and value should not contain `[\r\n]`.

**Comment by emersion** [comment]
This plan looks good to me.
