### ISSUE TITLE
returning error on len(line) > maxLineOctets can lead to missing attachments 

### ISSUE THREAD

**Issue by ekrem95** [emersion/go-message#81]
Inside `readLineSlice` function:
```
if len(line) > maxLineOctets {
	return nil, TooBigError{"line"}
}
```
This implementation is very useful to ignore the contents that can be spam, however it can cause caller to skip next attachment files in a mail message. Is it possible to use `break` instead of returning with an error here ?

**Comment by foxcpp** [comment]
What is the exact problem you are facing? maxLineOctets is 4 times bigger than the line length allowed by RFC 5322 and I fail to see how using `break` to just stop reading (and failing silently!) can help you return to a valid state.

**Comment by ekrem95** [comment]
The problem is actually inside the email file I am processing which has the PDF attachment file I am looking for after line length exceeds `maxLineOctets` number. I haven't realized the issue before https://github.com/emersion/go-message/commit/9c4415ed8676c8c7a266e0c1713ffb104f51637d is merged. So now I am wondering if we could ignore this issue to be able to capture attachment files in this kind of situations, if not, I believe the current implementation is good and my suggestion might not be necessary.

**Comment by foxcpp** [comment]
That length limitation is applied only to header fields. It does not affect body (your PDF attachment) of the message in any way.

**Comment by ekrem95** [comment]
Thank you @foxcpp for informative answers. Yes, length limitation is applied to headers and after error is returned, we break out of the loop in `readContinuedLineSlice` function and after that point I am unable to capture the file.

Would it be possible to have `MaxLineOctets` as a variable which we can set to different values according to our needs. Similar to `charset.RegisterEncoding` where we can register additional encodings.

**Comment by foxcpp** [comment]
Okay, just to be sure, you goal is to find the start of the message body (or multipart element) with malformed header (too long lines), right? I think it is possible to make MaxLineOctets changeable, but I would prefer to not have have it as a global variable but as an additional argument passed to ReadHeader. Probably via structure to allow further extensions. Something like that could work:
```go
type Readopts struct{
    MaxLineOctets int
}
func ReadHeader(*bufio.Reader, ReadOpts) (Header, error)
```
In any case, make a PR with changes you think are needed. Note that we are fine with changing existing functions and interfaces since go-message is 0.X and its API is not considered to be stable.

**Comment by foxcpp** [comment]
I thought you might as well just skip header parsing as I did in go-imap-sql: https://github.com/foxcpp/go-imap-sql/blob/d7d4cb3f7d1d88e528ee75a0ea5a1489699a5e16/fetch.go#L271
But then I realized you probably need that in multipart handling code: https://github.com/emersion/go-message/blob/fee642d7ffc287ff5416d41fe416ec83000c7fb8/textproto/multipart.go#L87

**Comment by ekrem95** [comment]
> Okay, just to be sure, you goal is to find the start of the message body (or multipart element) with malformed header (too long lines), right?

Yes.

I will get back to this discussion or open a PR after trying out your suggestions.

**Comment by emersion** [comment]
Out of curiosity, which header field is too big?

**Comment by ekrem95** [comment]
It is `References` header and its length as of today is `14958`.

An example of the header is:

```
References: <201810171846137868852@companyname.net>, <201810181911559950580@companyname.net>, <201810191839074079370@companyname.net>, <201810221914107070610@companyname.net>, <201810231848352870410@companyname.net>, <201810241847403360700@companyname.net>, <201810251909339254340@companyname.net>, <201810261915227601250@companyname.net>, <201810291935584398760@companyname.net>, <201810301844520105920@companyname.net>, <201810311913414232120@companyname.net>, <201811011904552385570@companyname.net>, <201811021904011409880@companyname.net>, <201811052043175068510@companyname.net>, <201811061859281629440@companyname.net>, <201811071932336785950@companyname.net>, <201811081919409655060@companyname.net>,
```

**Comment by emersion** [comment]
Created https://github.com/emersion/go-message/pull/123 which should make it easier to implement read options.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/go-message/pull/123
