### ISSUE TITLE
RFC 2047 (Non-ASCII Text in message headers)

### ISSUE THREAD

**Issue by grmat** [emersion/go-message#98]
Hi,

running the [example in the go-imap wiki](https://github.com/emersion/go-imap/wiki/Fetching-messages), I've seen that my name (example: "Nameß") in the `From: ` field looks like 

`=?utf-8?q?Name=C3=9F?=`

It seems like this is defined in https://tools.ietf.org/html/rfc2047 (section 2 and 4.2) as "similar to quoted-printable". 

in [`address.go`](https://github.com/emersion/go-message/blob/d512711/mail/address.go#L14), the documentation is:

```
// String formats the address as a valid RFC 5322 address. If the address's name
// contains non-ASCII characters the name will be rendered according to
// RFC 2047.
```

Now I'm not sure if I my assumption is correctl but shouldn't "rendered according to RFC 2047" mean that the string is decoded by the lib? Or does it imply that it will remain encoded and I have to do the decoding on my side?

**Comment by emersion** [comment]
The `mail.Address` fields are decoded, but the value returned by the `String` method is encoded.
