### ISSUE TITLE
allow callers to handle unknown encoding errors

### ISSUE THREAD

**Issue by jeffrom** [emersion/go-message#99]
Hello,

Would folks be willing to make it possible to handle unknown encoding errors? I'm working on [this aerc patch](https://lists.sr.ht/~sircmpwn/aerc/patches/11811) to handle messages with unknown encoding, and this change to go-message would give me an easy way to resolve it, afaict. I see that error handling is possible for unknown charsets via `IsUnknownCharset`. Would you accept a PR to make `isUnknownEncoding` public?

Thank you!

**Comment by emersion** [comment]
Encodings aren't like charsets, when they are wrong the whole message is unreadable. Also they are just 3 of them widely used.

Do you receive messages with unsupported encodings? Which encodings?

**Comment by jeffrom** [comment]
Thank you for that clarification. I do receive messages from time to time with unsupported encodings, i'd wager they're all spam, but still want to handle them in aerc. The one I'm looking at now is `Hexa`. There's an example message in the patch linked above.

**Comment by emersion** [comment]
I see. Then I agree it makes sense to expose `isUnknownEncoding` as you suggested.

**Comment by jeffrom** [comment]
thank you very much!
